Update build-slides.yml

diff --git a/.github/workflows/build-slides.yml b/.github/workflows/build-slides.yml
--- a/.github/workflows/build-slides.yml
+++ b/.github/workflows/build-slides.yml
@@ -15,16 +15,27 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: '3.12'
-      - name: Install dependencies
+      - name: Build slides
         run: | 
+          # abort on errors
+          set -e
+
+          # Install dependencies
           python -m pip install --upgrade pip
           python -m pip install git+https://gitlab.com/da_doomer/markdown-slides.git@fd27dd09cf90f00093a393338e08953c8d65d68e
-          mdslides slides.md --output_dir .
-      - name: Configure github
-        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
-      - name: Commit BUMP Version & Push
-        run: |
-          git add dist/* plugin/* LICENSE index.html
-          git commit -m "Deploy slides"
-          git checkout gh-pages
-          git push origin gh-pages
+          mkdir -p slides
+          mdslides slides.md --output_dir ./slides/
+          cd slides
+          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
+          git init
+          git add -A
+          git commit -m "Build slides"
+          cd ..
+            
+      - name: Force push to destination branch
+        uses: ad-m/github-push-action@v0.5.0
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: gh-pages
+          force: true
+          directory: slides
